FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04

ARG PYTHON_VERSION=3.5
ARG WITH_TORCHVISION=1

RUN apt update && apt install -y \
        software-properties-common \
        git \
        curl \
        nano \
        python3-pip \
        libgl1-mesa-glx

RUN add-apt-repository ppa:deadsnakes/ppa -y && apt-get update
RUN add-apt-repository ppa:mystic-mirage/pycharm

RUN apt-get update && apt-get install -y \
        python3-pip \
        libsm6 \
        libxext6 \
        libxrender-dev \
        libxi6 \
        libgconf-2-4 \
        python3-tk \
        zsh \
        wget

RUN pip3 install \
        numpy \
        torch==1.3.0 \
        pip==18.1 \
        opencv-python \
        imageio \
        matplotlib==2.1.0 \
        termcolor \
        torchvision==0.2.2 \
        scipy \
        pyyaml \
        cython \
        polyaxon-cli

RUN pip3 install \
    pycocotools

ADD ./* /code/
ENV PYTHONPATH="/code:${PYTHONPATH}"
WORKDIR /code